// Bundle the ordered source styles into one request for the published site.
import { build } from "esbuild";

await build({
  entryPoints: ["css/src/styles.css"],
  outfile: "css/styles.css",
  bundle: true,
  minifySyntax: true,
  legalComments: "inline",
  banner: { css: "/* Generated by npm run build:styles. Edit css/src/ instead. */" },
});
