// Build the maintained JavaScript modules into the single script used by GitHub Pages.
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const sourceRoot = path.join(root, "js", "src");

const result = await build({
  entryPoints: ["frontdoor-app"],
  write: false,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  legalComments: "none",
  banner: { js: "// Generated by npm run build:app. Edit js/src/ instead." },
  // Resolve this local-only source tree explicitly. The bundler does not need
  // to inspect parent directories for packages or configuration files.
  plugins: [{
    name: "local-source",
    setup(builder) {
      builder.onResolve({ filter: /.*/ }, (args) => {
        const filename = args.kind === "entry-point"
          ? path.join(sourceRoot, "app.mjs")
          : path.resolve(path.dirname(args.importer), args.path);
        const relative = path.relative(sourceRoot, filename);
        if (relative.startsWith("..") || path.isAbsolute(relative)) {
          return { errors: [{ text: `Import is outside the application source: ${args.path}` }] };
        }
        return { path: filename, namespace: "local-source" };
      });
      builder.onLoad({ filter: /.*/, namespace: "local-source" }, async (args) => ({
        contents: await readFile(args.path, "utf8"), loader: "js",
      }));
    },
  }],
});

await writeFile(path.join(root, "js", "main.js"), result.outputFiles[0].contents);
